dapl_ckeditor/app_ckeditor/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('home/', views.home, name='home'),
    path('blog/', views.blog, name='blog'),
    path('blog_list/', views.blog_list, name='blog_list'),
    path('blog_details/<int:pk>/', views.blog_detail_view, name='blog_details'),
    path('blog_edit/<int:pk>/', views.blog_edit_view, name='blog_edit'),
    path('blog_delete/<int:pk>/', views.blog_delete, name='blog_delete')
]

dapl_ckeditor/dapl_ckeditor/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include(('app_ckeditor.urls', 'app_ckeditor'), namespace='app_ckeditor'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dapl_ckeditor/app_ckeditor/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from django.core.files.storage import FileSystemStorage
from django.conf import settings

upload_storage = FileSystemStorage(location=settings.MEDIA_ROOT)


# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=200)
    content = RichTextUploadingField()
    featured_image = models.ImageField(default="", blank=True, upload_to='image')
    publish = models.BooleanField(default=True)

    def __str__(self):
        return self.title

dapl_ckeditor/app_ckeditor/forms.py
from django import forms
from django.forms import forms
from django.forms import ModelForm
from .models import *


class BlogForm(ModelForm):
    class Meta:
        model = Blog
        fields = '__all__'

dapl_ckeditor/app_ckeditor/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from .models import Blog
from .forms import BlogForm


# Create your views here.

def home(request):
    return render(request, 'app_ckeditor/home.html')


def blog(request):
    if request.method == 'GET':
        form = BlogForm()
        return render(request, 'app_ckeditor/blog.html', {"form": form})
    elif request.method == 'POST':
        print(request.FILES)
        form = BlogForm(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.featured_image = form.cleaned_data['featured_image']
            instance.save()
            return HttpResponseRedirect(reverse_lazy('app_ckeditor:blog_list'))


def blog_list(request):
    blogs = Blog.objects.all()
    print(blogs)
    for blog in blogs:
        print(blog.featured_image)
    return render(request, 'app_ckeditor/blog_list.html', {"blogs": blogs})

def blog_detail_view(request, pk):
    blog = get_object_or_404(Blog, pk=pk)
    context = {'blog': blog}
    return render(request, 'app_ckeditor/blog_details.html', context)


def blog_edit_view(request, pk):
    blog = get_object_or_404(Blog, pk=pk)
    form = BlogForm(request.POST or None, request.FILES or None, instance=blog)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse_lazy('app_ckeditor:blog_list'))
    else:
        return render(request, 'app_ckeditor/blog_edit.html', {"form": form})


def blog_delete(request, pk):
    blog = get_object_or_404(Blog, pk=pk)
    blog.delete()
    return HttpResponseRedirect(reverse_lazy('app_ckeditor:blog_list'))

dapl_ckeditor/app_ckeditor/templates/app_ckeditor/blog.html
{% extends 'app_ckeditor/dashboard.html' %}
{% block body %}
<div class="container" style="text-allign:center">
    <h2>Create Blog </h2>
    <div class="container-fluid">
        <form class="form-group" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media }}
            {{ form.as_p }}
            <input type="submit" style="background-color:green; color:white">
        </form>

    </div>

</div>

</div>

{% endblock %}

dapl_ckeditor/app_ckeditor/templates/app_ckeditor/blog_details.html
{% extends 'app_ckeditor/dashboard.html' %}
{% block body %}
<div class="container" style="text-allign:center">
    <div class="container-fluid">
        <h2>{{blog.title}}</h2>
        <p>{{blog.content|safe}}</p><br>
    </div>
    {% if request.user.is_authenticated %}
    <a href="{% url 'app_ckeditor:blog_edit' pk=blog.id %}">
        <button class="glyphicon glyphicon-pencil">Edit</button>
    </a>
    <a href="{% url 'app_ckeditor:blog_delete' pk=blog.id %}">
       <button class="glyphicon glyphicon-trash">Delete</button>
    </a>
    {% endif %}
</div>
{% endblock %}

dapl_ckeditor/app_ckeditor/templates/app_ckeditor/blog_edit.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <!--<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>-->
    <!--<script type="text/javascript" src="{% static " ckeditor/ckeditor-init.js" %}"></script>-->
    <!--<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>-->
</head>
<body>
<form class="form-group" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.media }}
    {{ form.as_p }}
    <input type="submit" style="background-color:green; color:white">
</form>
</body>
</html>

dapl_ckeditor/app_ckeditor/templates/app_ckeditor/blog_list.html
{% extends 'app_ckeditor/dashboard.html' %}
{% block body %}

<style>
    .search__part{float: right; width: auto;}
.search__part .userinput{width: auto; margin-right: 16px;}
#example1 {
    border: 2px solid #e0d9d9;
    padding: 20px;
    border-radius: 30px
    }


</style>


<div class="profileUser">
    <form action="/blog_list/" method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="search__part">
            <input class="userinput" type="text" size="40" name="search_value" value="" id="searchbar"
                   placeholder="search your blog">
            <input type="submit" value="Search"/>
        </div>
    </form>
</div>
<div class="container" style="text-allign:center">
    <h2>Blog List </h2>
    <div class="container-fluid">

        {% for blog in blogs %}


        <div id="example1" class="card text-black" style="max-width: 50rem;margin: 25px;">

            {% if blog.featured_image %}
            <img class="card-img-top" src="{{blog.featured_image.url}}" alt="Card image cap" style="width: 180px;
    height: 110px;">
            {% else %}
            <img class="card-img-top" src="" alt="Card image cap">
            {% endif %}
            <div class="card-body">
                <h5 class="card-title" style="font-size:40px"><a href="{% url 'app_ckeditor:blog_details' pk=blog.id%}"><b>{{blog.title}}</b></a>
                </h5>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the
                    card's content.</p>
            </div>
        </div>
        </span>


        {% endfor %}
    </div>

    {% endblock %}

</div>

dapl_ckeditor/app_ckeditor/templates/app_ckeditor/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Blog</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<body>
{% include 'app_ckeditor/side_navbar.html' %}

{% block body %}
{% endblock %}

</body>
</html>

dapl_ckeditor/app_ckeditor/templates/app_ckeditor/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Blog</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
{% include 'app_ckeditor/home_side_navbar.html' %}
<style>
    body{ margin:0; font:normal 75% Arial, Helvetica, sans-serif; }
    canvas{ display: block; vertical-align: bottom; }
    #particles-js{ position:absolute; top: 0px; left: 0px; z-index: -1; width: 100%; height: 100%; background-color: #323840; background-image: url(""); background-repeat: no-repeat; background-size: cover; background-position: 50% 50%; }
    .count-particles{ background: #000022; position: absolute; top: 48px; left: 0; width: 80px; color: #13E8E9; font-size: .8em; text-align: left; text-indent: 4px; line-height: 14px; padding-bottom: 2px; font-family: Helvetica, Arial, sans-serif; font-weight: bold; }
    .js-count-particles{ font-size: 1.1em; }
    #stats, .count-particles{ -webkit-user-select: none; margin-top: 5px; margin-left: 5px; }
    #stats{ border-radius: 3px 3px 0 0; overflow: hidden; }
    .count-particles{ border-radius: 0 0 3px 3px; }
    .jumbotron {
            display: table-cell;
            vertical-align: middle;
            horizontal-align: middle;
            }




</style>

<div id="particles-js" style="background-color:black"></div>
<!--<div class="count-particles"> <span class="js-count-particles">&#45;&#45;</span> particles </div>-->

<div class="container">
    <div class="jumbotron">
        <h1>This is a Simple Blog</h1>
    </div>
</div>

<!--{% for blog in blogs %}-->
<!--<a class="post" href="#">-->
<!--<div class="blog__title">-->
<!--{{blog.title}}-->
<!--</div>-->

<!--</a>-->
<!--{% endfor %}-->

<script src="https://cdn.jsdelivr.net/particles.js/2.0.0/particles.min.js"></script>
<script src="https://threejs.org/examples/js/libs/stats.min.js"></script>

<script>
    particlesJS("particles-js", {
      "particles": {
        "number": {
          "value": 88,
          "density": {
            "enable": true,
            "value_area": 700
          }
        },
        "color": {
          "value": ["#aa73ff", "#f8c210", "#83d238", "#33b1f8"]
        },
        "shape": {
          "type": "circle",
          "stroke": {
            "width": 0,
            "color": "#000000"
          },
          "polygon": {
            "nb_sides": 15
          }
        },
        "opacity": {
          "value": 0.5,
          "random": false,
          "anim": {
            "enable": false,
            "speed": 1.5,
            "opacity_min": 0.15,
            "sync": false
          }
        },
        "size": {
          "value": 2.5,
          "random": false,
          "anim": {
            "enable": true,
            "speed": 2,
            "size_min": 0.15,
            "sync": false
          }
        },
        "line_linked": {
          "enable": true,
          "distance": 110,
          "color": "#33b1f8",
          "opacity": 0.25,
          "width": 1
        },
        "move": {
          "enable": true,
          "speed": 1.6,
          "direction": "none",
          "random": false,
          "straight": false,
          "out_mode": "out",
          "bounce": false,
          "attract": {
            "enable": false,
            "rotateX": 600,
            "rotateY": 1200
          }
        }
      },
      "interactivity": {
        "detect_on": "canvas",
        "events": {
          "onhover": {
            "enable": false,
            "mode": "repulse"
          },
          "onclick": {
            "enable": false,
            "mode": "push"
          },
          "resize": true
        },
        "modes": {
          "grab": {
            "distance": 400,
            "line_linked": {
              "opacity": 1
            }
          },
          "bubble": {
            "distance": 400,
            "size": 40,
            "duration": 2,
            "opacity": 8,
            "speed": 3
          },
          "repulse": {
            "distance": 200,
            "duration": 0.4
          },
          "push": {
            "particles_nb": 4
          },
          "remove": {
            "particles_nb": 2
          }
        }
      },
      "retina_detect": true
    });

    <!--var count_particles, stats, update;-->
    <!--stats = new Stats;-->
    <!--stats.setMode(0);-->
    <!--stats.domElement.style.position = 'absolute';-->
    <!--stats.domElement.style.left = '0px';-->
    <!--stats.domElement.style.top = '0px';-->
    <!--document.body.appendChild(stats.domElement);-->
    <!--count_particles = document.querySelector('.js-count-particles');-->
    <!--update = function() {-->
      <!--stats.begin();-->
      <!--stats.end();-->
      <!--if (window.pJSDom[0].pJS.particles && window.pJSDom[0].pJS.particles.array) {-->
        <!--count_particles.innerText = window.pJSDom[0].pJS.particles.array.length;-->
      <!--}-->
      <!--requestAnimationFrame(update);-->
    <!--};-->
    <!--requestAnimationFrame(update);-->




</script>
</body>
</html>

dapl_ckeditor/app_ckeditor/templates/app_ckeditor/home_side_navbar.html
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
body {
    font-family: "Lato", sans-serif;
}

.sidenav {
    height: 100%;
    width: 0;
    position: fixed;
    z-index: 1;
    top: 0;
    left: 0;
    background-color: #111;
    overflow-x: hidden;
    transition: 0.5s;
    padding-top: 60px;
}

.sidenav a {
    padding: 8px 8px 8px 32px;
    text-decoration: none;
    font-size: 25px;
    color: #818181;
    display: block;
    transition: 0.3s;
}

.sidenav a:hover {
    color: #f1f1f1;
}

.sidenav .closebtn {
    position: absolute;
    top: 0;
    right: 25px;
    font-size: 36px;
    margin-left: 50px;
}

#main {
    transition: margin-left .5s;
    padding: 16px;
}

@media screen and (max-height: 450px) {
  .sidenav {padding-top: 15px;}
  .sidenav a {font-size: 18px;}
}

    </style>
</head>
<body>

<div id="mySidenav" class="sidenav">
    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
    <a href="{% url 'app_ckeditor:home' %}">Home</a>
    {% if request.user.is_authenticated %}
    <a href="{% url 'app_ckeditor:blog' %}">Create Blog</a>
    {% endif %}
    <a href="{% url 'app_ckeditor:blog_list' %}">Blog List</a>
    <a href="#">Profile</a>
    <a href="#">Contact</a>
</div>


<div id="main">
    <span style="font-size:30px;cursor:pointer;color: #fbfbfb;" onclick="openNav()">&#9776; open</span>
</div>

<script>
function openNav() {
    document.getElementById("mySidenav").style.width = "250px";
    document.getElementById("main").style.marginLeft = "250px";
}

function closeNav() {
    document.getElementById("mySidenav").style.width = "0";
    document.getElementById("main").style.marginLeft= "0";
}

</script>

</body>
</html>

dapl_ckeditor/app_ckeditor/templates/app_ckeditor/side_navbar.html
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
body {
    font-family: "Lato", sans-serif;
}

.sidenav {
    height: 100%;
    width: 0;
    position: fixed;
    z-index: 1;
    top: 0;
    left: 0;
    background-color: #111;
    overflow-x: hidden;
    transition: 0.5s;
    padding-top: 60px;
}

.sidenav a {
    padding: 8px 8px 8px 32px;
    text-decoration: none;
    font-size: 25px;
    color: #818181;
    display: block;
    transition: 0.3s;
}

.sidenav a:hover {
    color: #f1f1f1;
}

.sidenav .closebtn {
    position: absolute;
    top: 0;
    right: 25px;
    font-size: 36px;
    margin-left: 50px;
}

#main {
    transition: margin-left .5s;
    padding: 16px;
}

@media screen and (max-height: 450px) {
  .sidenav {padding-top: 15px;}
  .sidenav a {font-size: 18px;}
}

    </style>
</head>
<body>

<div id="mySidenav" class="sidenav">
    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
    <a href="{% url 'app_ckeditor:home' %}">Home</a>
    {% if request.user.is_authenticated %}
    <a href="{% url 'app_ckeditor:blog' %}">Create Blog</a>
    {% endif %}
    <a href="{% url 'app_ckeditor:blog_list' %}">Blog List</a>
    <a href="#">Profile</a>
    <a href="#">Contact</a>
</div>


<div id="main">
    <span style="font-size:30px;cursor:pointer;color: #333;" onclick="openNav()">&#9776; open</span>
</div>

<script>
function openNav() {
    document.getElementById("mySidenav").style.width = "250px";
    document.getElementById("main").style.marginLeft = "250px";
}

function closeNav() {
    document.getElementById("mySidenav").style.width = "0";
    document.getElementById("main").style.marginLeft= "0";
}

</script>

</body>
</html>